#we are learing about taking input from user
# print("Enter yout name please")
a = input("Enter your name please :")
print("My name is ", a)
x = input("Enter the first number :")
y = input("Enter the second number:")
print("The sum of " ,x,"and ", y, "is : ",int(x) + int(y))
print(int(x) + int(y))
z = input("Enter you father name: ")
print("Your Father name is",z)
print("Your Father name is " + z)
print("Enter your age:")
n = input()
print("Your age is:",n)